// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atomicaxis.ctlg_app.domain;

import com.atomicaxis.ctlg_app.domain.MarketingData;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MarketingData_Roo_Configurable {
    
    declare @type: MarketingData: @Configurable;
    
}
