// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atomicaxis.ctlg_app.domain;

import com.atomicaxis.ctlg_app.domain.ActionPlan;
import com.atomicaxis.ctlg_app.domain.ActionPlanDataOnDemand;
import com.atomicaxis.ctlg_app.domain.ContactRecordDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ActionPlanDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ActionPlanDataOnDemand: @Component;
    
    private Random ActionPlanDataOnDemand.rnd = new SecureRandom();
    
    private List<ActionPlan> ActionPlanDataOnDemand.data;
    
    @Autowired
    ContactRecordDataOnDemand ActionPlanDataOnDemand.contactRecordDataOnDemand;
    
    public ActionPlan ActionPlanDataOnDemand.getNewTransientActionPlan(int index) {
        ActionPlan obj = new ActionPlan();
        setName(obj, index);
        return obj;
    }
    
    public void ActionPlanDataOnDemand.setName(ActionPlan obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public ActionPlan ActionPlanDataOnDemand.getSpecificActionPlan(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ActionPlan obj = data.get(index);
        Long id = obj.getId();
        return ActionPlan.findActionPlan(id);
    }
    
    public ActionPlan ActionPlanDataOnDemand.getRandomActionPlan() {
        init();
        ActionPlan obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ActionPlan.findActionPlan(id);
    }
    
    public boolean ActionPlanDataOnDemand.modifyActionPlan(ActionPlan obj) {
        return false;
    }
    
    public void ActionPlanDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ActionPlan.findActionPlanEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ActionPlan' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ActionPlan>();
        for (int i = 0; i < 10; i++) {
            ActionPlan obj = getNewTransientActionPlan(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
