// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atomicaxis.ctlg_app.domain;

import com.atomicaxis.ctlg_app.domain.ContactRecord;
import com.atomicaxis.ctlg_app.domain.ContactRecordDataOnDemand;
import com.atomicaxis.ctlg_app.domain.ContactRecordIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ContactRecordIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ContactRecordIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ContactRecordIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ContactRecordIntegrationTest: @Transactional;
    
    @Autowired
    ContactRecordDataOnDemand ContactRecordIntegrationTest.dod;
    
    @Test
    public void ContactRecordIntegrationTest.testCountContactRecords() {
        Assert.assertNotNull("Data on demand for 'ContactRecord' failed to initialize correctly", dod.getRandomContactRecord());
        long count = ContactRecord.countContactRecords();
        Assert.assertTrue("Counter for 'ContactRecord' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ContactRecordIntegrationTest.testFindContactRecord() {
        ContactRecord obj = dod.getRandomContactRecord();
        Assert.assertNotNull("Data on demand for 'ContactRecord' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContactRecord' failed to provide an identifier", id);
        obj = ContactRecord.findContactRecord(id);
        Assert.assertNotNull("Find method for 'ContactRecord' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ContactRecord' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ContactRecordIntegrationTest.testFindAllContactRecords() {
        Assert.assertNotNull("Data on demand for 'ContactRecord' failed to initialize correctly", dod.getRandomContactRecord());
        long count = ContactRecord.countContactRecords();
        Assert.assertTrue("Too expensive to perform a find all test for 'ContactRecord', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ContactRecord> result = ContactRecord.findAllContactRecords();
        Assert.assertNotNull("Find all method for 'ContactRecord' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ContactRecord' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ContactRecordIntegrationTest.testFindContactRecordEntries() {
        Assert.assertNotNull("Data on demand for 'ContactRecord' failed to initialize correctly", dod.getRandomContactRecord());
        long count = ContactRecord.countContactRecords();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ContactRecord> result = ContactRecord.findContactRecordEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ContactRecord' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ContactRecord' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ContactRecordIntegrationTest.testFlush() {
        ContactRecord obj = dod.getRandomContactRecord();
        Assert.assertNotNull("Data on demand for 'ContactRecord' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContactRecord' failed to provide an identifier", id);
        obj = ContactRecord.findContactRecord(id);
        Assert.assertNotNull("Find method for 'ContactRecord' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyContactRecord(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ContactRecord' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContactRecordIntegrationTest.testMergeUpdate() {
        ContactRecord obj = dod.getRandomContactRecord();
        Assert.assertNotNull("Data on demand for 'ContactRecord' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContactRecord' failed to provide an identifier", id);
        obj = ContactRecord.findContactRecord(id);
        boolean modified =  dod.modifyContactRecord(obj);
        Integer currentVersion = obj.getVersion();
        ContactRecord merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ContactRecord' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ContactRecordIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ContactRecord' failed to initialize correctly", dod.getRandomContactRecord());
        ContactRecord obj = dod.getNewTransientContactRecord(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ContactRecord' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ContactRecord' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ContactRecord' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ContactRecordIntegrationTest.testRemove() {
        ContactRecord obj = dod.getRandomContactRecord();
        Assert.assertNotNull("Data on demand for 'ContactRecord' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ContactRecord' failed to provide an identifier", id);
        obj = ContactRecord.findContactRecord(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ContactRecord' with identifier '" + id + "'", ContactRecord.findContactRecord(id));
    }
    
}
