// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atomicaxis.ctlg_app.domain;

import com.atomicaxis.ctlg_app.domain.MarketingData;
import com.atomicaxis.ctlg_app.domain.MarketingDataDataOnDemand;
import com.atomicaxis.ctlg_app.domain.MarketingDataIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MarketingDataIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MarketingDataIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MarketingDataIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MarketingDataIntegrationTest: @Transactional;
    
    @Autowired
    MarketingDataDataOnDemand MarketingDataIntegrationTest.dod;
    
    @Test
    public void MarketingDataIntegrationTest.testCountMarketingDatas() {
        Assert.assertNotNull("Data on demand for 'MarketingData' failed to initialize correctly", dod.getRandomMarketingData());
        long count = MarketingData.countMarketingDatas();
        Assert.assertTrue("Counter for 'MarketingData' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MarketingDataIntegrationTest.testFindMarketingData() {
        MarketingData obj = dod.getRandomMarketingData();
        Assert.assertNotNull("Data on demand for 'MarketingData' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MarketingData' failed to provide an identifier", id);
        obj = MarketingData.findMarketingData(id);
        Assert.assertNotNull("Find method for 'MarketingData' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'MarketingData' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MarketingDataIntegrationTest.testFindAllMarketingDatas() {
        Assert.assertNotNull("Data on demand for 'MarketingData' failed to initialize correctly", dod.getRandomMarketingData());
        long count = MarketingData.countMarketingDatas();
        Assert.assertTrue("Too expensive to perform a find all test for 'MarketingData', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<MarketingData> result = MarketingData.findAllMarketingDatas();
        Assert.assertNotNull("Find all method for 'MarketingData' illegally returned null", result);
        Assert.assertTrue("Find all method for 'MarketingData' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MarketingDataIntegrationTest.testFindMarketingDataEntries() {
        Assert.assertNotNull("Data on demand for 'MarketingData' failed to initialize correctly", dod.getRandomMarketingData());
        long count = MarketingData.countMarketingDatas();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<MarketingData> result = MarketingData.findMarketingDataEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'MarketingData' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'MarketingData' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MarketingDataIntegrationTest.testFlush() {
        MarketingData obj = dod.getRandomMarketingData();
        Assert.assertNotNull("Data on demand for 'MarketingData' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MarketingData' failed to provide an identifier", id);
        obj = MarketingData.findMarketingData(id);
        Assert.assertNotNull("Find method for 'MarketingData' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMarketingData(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'MarketingData' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MarketingDataIntegrationTest.testMergeUpdate() {
        MarketingData obj = dod.getRandomMarketingData();
        Assert.assertNotNull("Data on demand for 'MarketingData' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MarketingData' failed to provide an identifier", id);
        obj = MarketingData.findMarketingData(id);
        boolean modified =  dod.modifyMarketingData(obj);
        Integer currentVersion = obj.getVersion();
        MarketingData merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'MarketingData' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MarketingDataIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'MarketingData' failed to initialize correctly", dod.getRandomMarketingData());
        MarketingData obj = dod.getNewTransientMarketingData(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'MarketingData' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'MarketingData' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'MarketingData' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MarketingDataIntegrationTest.testRemove() {
        MarketingData obj = dod.getRandomMarketingData();
        Assert.assertNotNull("Data on demand for 'MarketingData' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'MarketingData' failed to provide an identifier", id);
        obj = MarketingData.findMarketingData(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'MarketingData' with identifier '" + id + "'", MarketingData.findMarketingData(id));
    }
    
}
