// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atomicaxis.ctlg_app.domain;

import com.atomicaxis.ctlg_app.domain.ContactRecordDataOnDemand;
import com.atomicaxis.ctlg_app.domain.Note;
import com.atomicaxis.ctlg_app.domain.NoteDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect NoteDataOnDemand_Roo_DataOnDemand {
    
    declare @type: NoteDataOnDemand: @Component;
    
    private Random NoteDataOnDemand.rnd = new SecureRandom();
    
    private List<Note> NoteDataOnDemand.data;
    
    @Autowired
    ContactRecordDataOnDemand NoteDataOnDemand.contactRecordDataOnDemand;
    
    public Note NoteDataOnDemand.getNewTransientNote(int index) {
        Note obj = new Note();
        setAuthor(obj, index);
        setCreateDateTime(obj, index);
        setNoteText(obj, index);
        return obj;
    }
    
    public void NoteDataOnDemand.setAuthor(Note obj, int index) {
        String author = "author_" + index;
        obj.setAuthor(author);
    }
    
    public void NoteDataOnDemand.setCreateDateTime(Note obj, int index) {
        Date createDateTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreateDateTime(createDateTime);
    }
    
    public void NoteDataOnDemand.setNoteText(Note obj, int index) {
        String noteText = "noteText_" + index;
        obj.setNoteText(noteText);
    }
    
    public Note NoteDataOnDemand.getSpecificNote(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Note obj = data.get(index);
        Long id = obj.getId();
        return Note.findNote(id);
    }
    
    public Note NoteDataOnDemand.getRandomNote() {
        init();
        Note obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Note.findNote(id);
    }
    
    public boolean NoteDataOnDemand.modifyNote(Note obj) {
        return false;
    }
    
    public void NoteDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Note.findNoteEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Note' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Note>();
        for (int i = 0; i < 10; i++) {
            Note obj = getNewTransientNote(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
